services:
  - type: web
    name: drugbot
    env: python
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: cd drugbot && uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.8
